---
# Web server specific configuration
server_type: "web"

# Web server optimizations
common_sysctl_params:
  # Inherit from all.yml and add web-specific optimizations
  - key: net.core.somaxconn
    value: 32768
  - key: net.ipv4.tcp_max_syn_backlog
    value: 32768
  - key: net.ipv4.tcp_syncookies
    value: 1
  - key: net.ipv4.tcp_fin_timeout
    value: 15
  - key: net.ipv4.tcp_keepalive_time
    value: 300
  - key: net.ipv4.tcp_keepalive_intvl
    value: 30
  - key: net.ipv4.tcp_keepalive_probes
    value: 3

# Additional packages for web servers
common_packages_web:
  - nginx
  - certbot
  - python3-certbot-nginx
  - ufw
  - fail2ban

# Combine with base packages
common_packages: "{{ common_packages + common_packages_web }}"
